Gromacs update

diff --git a/Gromacs/standard/mkgmx-run b/Gromacs/standard/mkgmx-run
--- a/Gromacs/standard/mkgmx-run
+++ b/Gromacs/standard/mkgmx-run
@@ -1,30 +1,33 @@
 #!/bin/bash
 
 mkdir -p output
-mini1=true
-mini2=true
+mini=true
+double=false
 heat=true
 eq_npt=true
 md1=false
 md2=false
 
-if $mini1; then
-    prefix=step1_mini_crystal
+[ ! -d pdb2gmx ] && echo -e "mkgmx> Directory pdb2gmx not found!"; exit 1 
+[ ! -f pdb2gmx/index.ndx ] && echo -e "mkgmx> Index file not found!"; exit 1 
+
+if $mini; then
+    prefix=step1_mini
     rm -f $prefix.tpr
     gmx grompp -f $prefix.mdp -o output/$prefix.tpr -c pdb2gmx/ionized.pdb -r pdb2gmx/ionized.pdb -n pdb2gmx/index.ndx -p pdb2gmx/topol.top
     gmx mdrun -pin on -ntmpi 1 -ntomp 12 -v -deffnm output/$prefix
 fi
     
-if $mini2; then
-    prefix1=step1_mini_crystal
-    prefix2=step2_mini
+if $double; then
+    prefix1=step1_mini
+    prefix2=step1_mini_double
     rm -f $prefix2.tpr
     gmx_d grompp -f $prefix2.mdp -o output/$prefix2.tpr -c output/$prefix1.gro -r pdb2gmx/ionized.pdb -n pdb2gmx/index.ndx -p pdb2gmx/topol.top
     gmx_d mdrun -pin on -ntmpi 1 -ntomp 12 -v -deffnm output/$prefix2
 fi
 
 if $heat; then
-    prefix1=step2_mini
+    prefix1=step1_mini
     prefix2=step3_annealing
     rm -f $prefix2.tpr
     gmx grompp -f $prefix2.mdp -o output/$prefix2.tpr -c output/$prefix1.gro -r pdb2gmx/ionized.pdb -n pdb2gmx/index.ndx -p pdb2gmx/topol.top
